[project]
name = "pytest-easy"
version = "0.0.5"
description = "Pytest, but made easy"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8,<3.14"

[project.urls]
Homepage = "https://github.com/Implosiv3/pytest-easy"
Issues = "https://github.com/Implosiv3/pytest-easy/issues"

[tool.poetry.dependencies]
# Mandatory
printer-easy = { version = ">=0.0.2,<1.0.0", optional = false }
python-dotenv = { version = ">=1.0.1,<9999.0.0", optional = false }
psutil = { version = ">=7.2.2,<9999.0.0", optional = false }
# Optional

[tool.poetry]
packages = [{include = "pytest_easy", from = "src"}]

[tool.poetry.group.optional]
optional = true

[tool.poetry.group.optional.dependencies]
numpy = { version = ">=0.0.1,<9999.0.0", optional = false }
pillow = { version = ">=0.0.1,<9999.0.0", optional = false }

[tool.poetry.group.dev.dependencies]
pytest = { version = "^8.3.5", optional = false }
pytest-asyncio = { version = ">=0.24.0", optional = false }

[tool.pytest.ini_options]
markers = [
    "mandatory: mandatory tests for release",
    "additional: exhaustive and demanding tests"
]
asyncio_default_fixture_loop_scope = 'function'

[tool.poetry.scripts]
pytest-easy-run-tests-isolated = "pytest_easy.cli.isolated_tests_runner:main"
pytest-easy-init-log-file = "pytest_easy.cli.init_log:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
